version: "3.8"

services:
  mongodb:
    hostname: mongo-1.mongo
    container_name: mongo-1.mongo
    image: mongo:4.4.8
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs0", "--journal", "--bind_ip_all" ]
    ports:
     - "27018:27017"
    volumes:
    - "./file.key:/data/file.key"
    networks:
      - mongo-net

  app:
    depends_on:
      - mongo-1.mongo
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

networks:
  mongo-net:
    name: mongo-net