version: "3.8"

services:
  mongodb:
    image: davybello/mongo-replica-set:4.4.8
    container_name: mongodb
    ports:
     - 27018:27018
    volumes:
    - "./docker/.data/mongo1:/var/lib/mongo1"
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: