version: "3.8"

services:
  mongodb:
    hostname: localhost
    image: mongo:4.4.8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
     - 27018:27018
    volumes:
    - "./file.key:/data/file.key"
    command : ["chmod", "600", "/data/file.key"]
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs0", "--journal", "--bind_ip_all" ]
    networks:
      - mongo-net

  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

networks:
  mongo-net:
    name: mongo-net