version: "3.8"

services:
  mongo-0.mongo:
    hostname: mongo-0.mongo
    container_name: mongo-0.mongo
    image: mongo:4.4.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs0 --journal --bind_ip_all" 
    ports:
    - "27017:27017"
    restart: always
    networks:
      - mongo-net
    volumes: 
    - "./setup.sh:/setup.sh"
    - "./file.key:/data/file.key"  

  app:
    depends_on:
      - mongo-0.mongo
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

networks:
  mongo-net:
    name: mongo-net