version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aymen
      - MONGO_INITDB_ROOT_PASSWORD=aymen
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./airQuality-app
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT=8081
    environment:
      - DB_NAME=airQuality
      - DB_PORT:$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: