version: "3.8"

services:
  mongodb:
    image: davybello/mongo-replica-set:4.4.8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
     - 27018:27018
    volumes:
     - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
   swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8085:8085"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - type: bind
        source: ./api/dist
        target: /swagger

volumes:
  db: